### ISSUE TITLE
[Kernel 5.3.5, Fedora 30] Empty visible wifi networks on v5.2.20 and v5.6.4.1

### ISSUE THREAD

**Issue by KirkBushman** [aircrack-ng/rtl8812au#445] opened 2019-10-16 08:28 UTC
I was on v5.3.4 driver before, I updated today to the linux kernel 5.3.5, and it doesn't show any visible network in the panel, I've then tried all the versions, even the ones that have the fix for kernel 5.3+, but nothing... 
Can't see any network.

**Comment by jhoward321** [comment] 2019-10-17 23:30
I can report having the same problem. Same kernel on Fedora 30.

**Comment by CLiNTPELiX** [comment] 2019-10-18 17:17
I'm having nearly same problems on latest Ubuntu 19.10 and Fedora 31 Beta.
I can see all channel in 2.4 GHz(b,g,n) and 5 GHz(ac) (but only channels below 56)

**Comment by felubra** [comment] 2019-10-19 14:05
I have the same problem in the 5.2.15-200.fc30.x86_64 kernel too.

**Comment by ortegahernandes** [comment] 2019-10-21 13:33
Here also does not appear wifi networks
Ubuntu 19.10 (kernel 5.3.0-19)

**Comment by ortegahernandes** [comment] 2019-10-21 13:35
Here also does not appear wifi networks
Ubuntu 19.10 (kernel 5.3.0-19)

**Comment by CGarces** [comment] 2019-10-21 17:27
Duplicate of #422

**Comment by kimocoder** [comment] 2019-10-30 20:02
Follow #422 the solution is there

**Closed as completed by kimocoder** 2019-10-30 20:02 UTC
