### ISSUE TITLE
device not working properly with kernel 5.12.5

### ISSUE THREAD

**Issue by vishytk** [aircrack-ng/rtl8812au#865] opened 2021-05-24 07:52 UTC
Fedora 34, Kernel 5.12.5 with the latest code.

The driver compiles and gets installed without any issue with the latest git pull. But the device does not connect to the access point, looks like the authentication is not happening for some reason.

When switched to older kernel 5.11.21 the device works perfectly.

**Comment by juceda** [comment] 2021-05-24 08:48
I confirm that. Just happened exactly the same to me too, when updated to 5.12.5.

**Comment by CGarces** [comment] 2021-05-24 09:48
Duplicate of #855
Please appy patch #857

**Comment by wawrzek** [comment] 2021-09-26 14:13
If it is a duplicate, it should be closed, shouldn't it?

**Closed as completed** 2021-12-12 21:45 UTC
