### ISSUE TITLE
error: implicit declaration of function 'cfg80211_sinfo_alloc_tid_stats'

### ISSUE THREAD

**Issue by iatsiuk** [aircrack-ng/rtl8812au#436] opened 2019-10-05 14:12 UTC
Module version: rtl8812au-v5.6.4.1
Rockchip RK3399 SOC

```
# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/7/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 7.4.0-1ubuntu1~18.04.1' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=aarch64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu
Thread model: posix
gcc version 7.4.0 (Ubuntu/Linaro 7.4.0-1ubuntu1~18.04.1)
```

```
# uname -a
Linux rockpro64 4.4.190-1233-rockchip-ayufan-gd3f1be0ed310 #1 SMP Wed Aug 28 08:59:34 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
```

```
# cat /etc/issue
Ubuntu 18.04.3 LTS \n \l
```

Errors:
```
  CC [M]  /home/rock64/rtl8812au-v5.6.4.1/os_dep/linux/rtw_cfgvendor.o
  CC [M]  /home/rock64/rtl8812au-v5.6.4.1/os_dep/linux/wifi_regd.o
  CC [M]  /home/rock64/rtl8812au-v5.6.4.1/os_dep/linux/rtw_android.o
  CC [M]  /home/rock64/rtl8812au-v5.6.4.1/os_dep/linux/rtw_rhashtable.o
  CC [M]  /home/rock64/rtl8812au-v5.6.4.1/os_dep/linux/ioctl_mp.o
/home/rock64/rtl8812au-v5.6.4.1/os_dep/linux/ioctl_cfg80211.c: In function 'rtw_cfg80211_indicate_sta_assoc':
/home/rock64/rtl8812au-v5.6.4.1/os_dep/linux/ioctl_cfg80211.c:4484:3: error: implicit declaration of function 'cfg80211_sinfo_alloc_tid_stats'; did you mean 'cfg80211_inform_bss_width'? [-Werror=implicit-function-declaration]
   cfg80211_sinfo_alloc_tid_stats(&sinfo, GFP_KERNEL);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   cfg80211_inform_bss_width
  CC [M]  /home/rock64/rtl8812au-v5.6.4.1/hal/hal_intf.o
/home/rock64/rtl8812au-v5.6.4.1/os_dep/linux/ioctl_cfg80211.c: At top level:
cc1: warning: unrecognized command line option '-Wno-cast-function-type'
cc1: warning: unrecognized command line option '-Wno-cast-function-type'
cc1: some warnings being treated as errors
  CC [M]  /home/rock64/rtl8812au-v5.6.4.1/hal/hal_com.o
  CC [M]  /home/rock64/rtl8812au-v5.6.4.1/hal/hal_com_phycfg.o
  CC [M]  /home/rock64/rtl8812au-v5.6.4.1/hal/hal_phy.o
scripts/Makefile.build:277: recipe for target '/home/rock64/rtl8812au-v5.6.4.1/os_dep/linux/ioctl_cfg80211.o' failed
make[2]: *** [/home/rock64/rtl8812au-v5.6.4.1/os_dep/linux/ioctl_cfg80211.o] Error 1
make[2]: *** Waiting for unfinished jobs....
Makefile:1479: recipe for target '_module_/home/rock64/rtl8812au-v5.6.4.1' failed
make[1]: *** [_module_/home/rock64/rtl8812au-v5.6.4.1] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.4.190-1233-rockchip-ayufan-gd3f1be0ed310'
Makefile:1608: recipe for target 'modules' failed
make: *** [modules] Error 2
```

Full build log:
[build.log.gz](https://github.com/aircrack-ng/rtl8812au/files/3693332/build.log.gz)

**Comment by CGarces** [comment] 2019-10-05 14:26
Duplicate of #419

**Closed as completed** 2019-10-06 13:19 UTC
